import type { Metadata } from 'next'
import { SessionProvider } from "next-auth/react";
import { Inter } from 'next/font/google'
import './globals.css'

import ToasterContext from '@/lib/toaster/ToasterContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <ToasterContext />
          {children}
        </SessionProvider>
      </body>
    </html>
  )
}
